
// Stored modelname (without quotes): "U:\dod\models\mapmodels\plants\compile\plant1.mdl"
$modelname "co_ether/plant1.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "plant1"
{
	studio "plant1"
}

$flags 0

$texrendermode "leaf2.bmp" masked

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Box01" -75.870003 -68.805 0 55.484997 76.860001 46.485001

$sequence "idle" {
	"plant1_anims\idle"
	fps 1
}
