
// Stored modelname (without quotes): "C:\GameDesign\Apps\HLModel\Models\machinarocks\machinarocks.mdl"
$modelname "ns_machina/machinarocks.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "body"
{
	studio "machinarocks_ref"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "GeoSphere5" -34127.621094 -14214.530273 -10242.950195 4905.25 17741.150391 21626.199219

$sequence "idle" {
	"machinarocks_anims\idle"
	fps 10
}
