
// Stored modelname (without quotes): "C:\SIERRA\Gehtto Mac 10\Tripod.mdl"
$modelname "ns_bast/tripod1.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "body"
{
	studio "reference"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Point_Holder" -25.969999 -37.419998 -24.030001 25.18 64.410004 12.67

$sequence "seq-name" {
	"tripod1_anims\seq-name"
	ACT_IDLE 1
	fps 50
	loop
}
