
// Stored modelname (without quotes): "C:\Furreal\models\htaogrenade\p_htao.mdl"
$modelname "p_gr.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "phtao"
}

$flags 0


$attachment 0 "Bip01 R Hand" 13 1 4

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Bip01 Neck" -2.869898 0 -4.140396 0 1.399663 0
$hbox 0 "Bip01 R Hand" 0 -0.01 -2.53 4.26 1.81 4.79

$sequence "idle" {
	"p_gr_anims\idle"
	fps 30
}
