
// Stored modelname (without quotes): "C:\Documents and Settings\drath\Desktop\helix.mdl"
$modelname "co_niveus/helix.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "body"
{
	studio "helixref"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "joint1" -23.969999 -93.07 -23.370001 22.889999 94.419998 23.5

$sequence "seq-name" {
	"helix_anims\seq-name"
	ACT_IDLE 1
	fps 30
	loop
}
