
// Stored modelname (without quotes): "C:\GameDesign\Apps\HLModel\Models\machinaship\machinaship_add.md"
$modelname "ns_machina/machinaship_add.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "body"
{
	studio "machinaship_add_ref"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Box04" -1371826.125 -1360000.25 0 1360000 1770984.875 2720009

$sequence "idle" {
	"machinaship_add_anims\idle"
	fps 10
}
