
// Stored modelname (without quotes): "F:\SIERRA\Half-Life\cstrike\models\czg_screen96.mdl"
$modelname "ns_tanith/czg_screen96.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "czg_screen96"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Box01" -96 -96 -0.5 0 0 0.5

$sequence "hologram" {
	"czg_screen96_anims\hologram"
	fps 10
	loop
}
